### ISSUE TITLE
As a <user>, I want to <click on the radio button> and <have the corresponding image display>.

### ISSUE THREAD

**Issue by rescriba01** [rescriba01/tribute#1]
**User Story**
As a User, I want to click on the radio button and for every click, the corresponding image should display.

![first click](https://user-images.githubusercontent.com/3300399/115733791-33b64e80-a357-11eb-8c34-b4b2700ff577.png)

![second click new radio button](https://user-images.githubusercontent.com/3300399/115734210-855ed900-a357-11eb-958c-094ecfa495cc.png)

![console difference](https://user-images.githubusercontent.com/3300399/115734313-9a3b6c80-a357-11eb-8610-579a27f51da4.png)

**Acceptance Criteria**
Every click of the radio buttons should show a new image (that which has been designated a match via the code).

**Comment by plamoni** [comment]
As discussed on Discord, the problem looks to be that `originalFig` is being replaced on the first click, but on subsequent clicks, it's trying to replace it again:

https://github.com/rescriba01/tribute/blob/9cabc101c5e82b98ce4e2227127ff8f32e6de514/resources/js/script.js#L62

So it doesn't switch the second time.

I've added a PR that renames `originalFig` to `currentFig` and updates it each time a new image is clicked.
